ifndef::imagesdir[:imagesdir: ../images]

[[section-architecture-constraints]]
== Restricciones de la arquitectura

Las restricciones de la arquitectura de este proyecto son las siguientes:

|===
| Restricción | Explicación

| Uso de Wikidata
| Se debe usar obligatoriamente la API de Wikidata para obtener los datos necesarios
para generar las preguntas y las respuestas dentro del juego.

| Despliegue
| La aplicación deberá consistir en una aplicación web, no pudiendo ser una aplicación
móvil o de escritorio.

| Acceso a datos mediante APIs
| El acceso a datos relacionados con los usuarios que participan y las respuestas
a las preguntas deberá realizarse con una API.

| Presupuesto reducido
| El presupuesto para el proyecto es limitado, reduciéndose únicamente a lo que
cada desarrollador esté dispuesto a desembolsar de su propio bolsillo.
|===


Consecuencias de las limitaciones:

* La aplicación web deberá estar suficientemente optimizada para su uso en
navegadores, atendiendo a aspectos relacionados con el rendimiento, la usabilidad
y la disponibilidad.
* El presupuesto reducido implicará un uso mayor de herramientas de código abierto,
reduciendo drásticamente el uso de software bajo licencia.
* El uso de Wikidata reducirá la carga de trabajo de la aplicación, al no tener
que trabajar sobre una base de datos local.
* Al usar la api de Wikidata somos dependientes de su disponiblidad y en caso 
de fallar tambien fallaria nuestra aplicación.

