ifndef::imagesdir[:imagesdir: ../images]

[[section-system-scope-and-context]]
== Alcance y contexto del sistema



[role="arc42help"]
****
Nuestro proyecto, denominado "WIQ", consiste en una simulación inspirada en el famoso juego de RTVE  "Saber y Ganar" (más información en: https://www.rtve.es/play/videos/saber-y-ganar/), en el cual los concursantes tienen la oportunidad de hacerse con una cantidad de dinero en función del número de respuestas acertadas a preguntas de diversas temáticas, con un límite establecido de tiempo para cada una de ellas.

La aplicación permitirá a los usuarios no solo acumular dinero al participar en la funcionalidad básica de juego de preguntas y respuestas, si no que cuenta también con otras funcionalidades como poder consultar su historial de juegos y el listado completo de usuarios registrados. 

****


=== Contexto de negocio

[role="arc42help"]
****
Al acceder a la página principal de la aplicación, los usuarios podrán ver una interfaz que les permitirá iniciar sesión para acceder a su cuenta. En caso de ser su primera vez y no tener cuenta, tendrá la opción de registrarse. Una vez autenticados, los usuarios se encontrarán con la opción tanto empezar un nuevo juego como de ver su historial 
de jugadas anteriores. 

Dentro del historial, este le mostrará el número de partidas totales realizadas y por cada una de ellas la fecha en la que se jugó, el número de respuestas acertadas, el dinero conseguido y el tiempo total 
que le llevó completarlo.

Aparte de eso también tendrán la opción de visualizar el listado completo de usuarios registrados hasta la fecha. 

****


=== Contexto técnico 

[role="arc42help"]
****
Para el desarrollo de este proyecto usaremos la API de Wikidata tanto para generar automaticamente las preguntas como para obtener 
las respuestas correctas a las mismas. 
Respecto al lenguaje de programación se usará JavaScript, utilizando React para el desarrollo del front-end. Además 
haremos uso de Node.js y la implementación de microservicios para el back-end. Respecto a la base de datos usaremos una NonSQL como MongoDB. 

|===
| Interfaz técnica | Explicación

| Wikidata
| API usada para generar automáticamente las preguntas y obtener su respuesta.

| JavaScript
| Lenguaje principal de la aplicación.

| React
| Librería JavaScript que nos permitirá construir la interfaz de la aplicación.

| MongoDB
| Base de datos NoSQL.

| Node.Js
| Entorno de servidor para tratar los endpoints.
|===

****

