ifndef::imagesdir[:imagesdir: ../images]

[[section-system-scope-and-context]]
== Alcance y contexto del sistema

Nuestro proyecto, denominado "WIQ", consiste en una simulación inspirada en el famoso juego de RTVE "Saber y Ganar" (más información en: https://www.rtve.es/play/videos/saber-y-ganar/), en el cual los concursantes tienen la oportunidad de hacerse con una cantidad de dinero en función del número de respuestas acertadas a preguntas de diversas temáticas, con un límite establecido de tiempo para cada una de ellas.

La aplicación permitirá a los usuarios no solo acumular dinero al participar en la funcionalidad básica de juego de preguntas y respuestas, funcionalidad la cual es personalizable, sino que cuenta también con las opciones de visualizar un ranking, poder consultar su historial de jugadas así como el listado completo de usuarios registrados entre otras más.



=== Contexto de negocio

Al acceder a la página principal de la aplicación, los usuarios podrán ver una interfaz que les permitirá iniciar sesión para acceder a su cuenta. En caso de ser su primera vez y no tener cuenta, tendrán la opción de registrarse. Una vez autenticados, los usuarios se encontrarán con la opción tanto de empezar un nuevo juego como de realizar otras operaciones que se pueden visualizar en la barra de navegación, como el historial de jugadas, el ranking y la opción de modificar los ajustes de la partida.

Dentro del historial, este les mostrará el número de partidas totales realizadas y, por cada una de ellas, la fecha en la que se jugó, el número de respuestas acertadas, el dinero conseguido y el tiempo total que les llevó completarlo.

En el ranking, podrán ver destacados los tres usuarios con mejor porcentaje de aciertos, así como las estadísticas del ranking de todos los usuarios.

Aparte de todo lo anterior, el administrador contará con la opción de visualizar el listado completo de usuarios registrados hasta la fecha, así como la posibilidad de ver todo el historial de preguntas que se han generado. 



=== Contexto técnico 

Para el desarrollo de este proyecto, utilizaremos la API de Wikidata tanto para generar automáticamente las preguntas como para obtener las respuestas correctas a las mismas. En cuanto al lenguaje de programación, se utilizará JavaScript, utilizando React para el desarrollo del front-end. Además, haremos uso de Node.js y la implementación de microservicios para el back-end. Respecto a la base de datos, usaremos una NoSQL como MongoDB.

|===
| Interfaz técnica | Explicación

| Wikidata
| API usada para generar automáticamente las preguntas y obtener su respuesta.

| JavaScript
| Lenguaje principal de la aplicación.

| React
| Librería JavaScript que nos permitirá construir la interfaz de la aplicación.

| MongoDB Cloud
| Base de datos NoSQL.

| Node.Js
| Entorno de servidor para tratar los endpoints.

| Azure
| Usado para el despliegue de la aplicación en la nube.
|===
